ALTER SEQUENCE ItemMenu_SEQ INCREMENT BY 1;
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Coxinha', 'Deliciosa coxinha de frango', 3.5);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Pastel', 'Pastel frito na hora', 2.5);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Caldo de Feijão', 'Saboroso caldo de feijão', 10.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Picanha', 'Picanha suculenta com fritas', 25.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Frango à Passarinho', 'Frango à passarinho crocante', 15.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Bolinho de Bacalhau', 'Tradicional bolinho de bacalhau', 4.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Mandioca Frita', 'Porção de mandioca frita', 10.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Feijoada', 'Feijoada completa servida com arroz e farofa', 30.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Moqueca de Peixe', 'Moqueca de peixe com pirão', 35.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Escondidinho de Carne', 'Escondidinho de carne com purê de mandioca', 20.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Torta de Limão', 'Deliciosa torta de limão', 6.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Brigadeiro', 'Docinho de brigadeiro', 1.5);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Caipirinha', 'Caipirinha de limão', 8.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Cerveja', 'Cerveja gelada', 5.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Batata Frita', 'Porção de batata frita', 10.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Pão de Alho', 'Pão de alho para acompanhar o churrasco', 4.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Churrasco Misto', 'Churrasco misto com carnes e linguiça', 30.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Acarajé', 'Tradicional acarajé baiano', 12.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Bobó de Camarão', 'Bobó de camarão servido com arroz', 40.0);
INSERT INTO ItemMenu (id, nome, descricao, preco) VALUES (nextval(ItemMenu_SEQ), 'Mousse de Maracujá', 'Mousse de maracujá para sobremesa', 6.0);
